# -*- coding: utf-8 -*-
"""RE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cf7xtwedagNhMhkYOZQmZTj4g6S6ILUz
"""

# ============================= FORM ============================= #
# @markdown <font size=5>← Create user</font>
username = "ddr91" #@param {type:"string"}
password = "123456qwerty" #@param {type:"string"}
# ================================================================ #

import os

print("Creating user and setting it up...")

# Creation of user
os.system(f"useradd -m {username}")

# Add user to sudo group
os.system(f"adduser {username} sudo")
    
# Set password of user to 'root'
os.system(f"echo '{username}:{password}' | sudo chpasswd")

# Change default shell from sh to bash
os.system("sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd")

print("User created and configured.")
#============================= FORM ============================= #
#@markdown <font size=5>← [Start] Remote Desktop</font>
#@markdown <ol>
#@markdown 	<li>Click <a href="http://remotedesktop.google.com/headless" target="_blank">HERE</a> (opens in new tab) and set up a computer first.</li>
#@markdown 	<li>After you have done setting up a computer, get the Debian Linux command / authcode and paste it into the field below.</li>
#@markdown 	<li>Run the cell and wait for it to finish.</li>
#@markdown 	<li>Now, go to <a href="http://remotedesktop.google.com/access" target="_blank">HERE</a> (opens in new tab) and you should see a machine pops up in there.</li>
#@markdown 	<li>Click on that machine to remote it and enter the pin.</li>
#@markdown </ol> 
CRP = "DISPLAY= /opt/google/chrome-remote-desktop/start-host --code=\"4/0AVHEtk4MZAAP4COufn8MdhFHJY98GDU1JbHGaIu4wOaUCwTM7q-SRX67g3f6PbSMrDHSDg\" --redirect-url=\"https://remotedesktop.google.com/_/oauthredirect\" --name=$(hostname)" #@param {type:"string"}

#@markdown Enter a PIN that is equal to or more than 6 digits
Pin = 111111 #@param {type: "integer"}

#@markdown > It takes about 4 to 5 minutes for the installation process.
#================================================================ #

import os
import subprocess


class CRD:
    def __init__(self):
        os.system("sudo apt update")
        self.finish()


    @staticmethod
    def finish():
        print("Finalizing...")
        os.system(f"adduser {username} chrome-remote-desktop")
        command = f"{CRP} --pin={Pin}"
        os.system(f"su - {username} -c '{command}'")
        print("Finished Succesfully!")


try:
    if username:
        if CRP == "":
            print("Please enter the authcode from the Chrome Remote Desktop site!")
        elif len(str(Pin)) < 6:
            print("Enter a PIN that is equal to or more than 6 digits!")
        else:
            CRD()
except NameError as e:
    print("Username variable not found! Create a user first!")